<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Dish;
Use Illuminate\Support\Str;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Dishes = [
            // McDonald
            [
                'id_genre' => 3,
                'id_restaurant' => 1,
                'name' => 'Spicy Gran Crispy McBacon',
                'description' => 'Se ami il Crispy McBacon, il nuovo Spicy Gran Crispy McBacon ti lascerà letteralmente a bocca aperta grazie alla salsa Crispy dal gusto Spicy, oltre agli ingredienti del classico: carne 100% bovina da allevamenti italiani, croccante bacon 100% da pancetta italiana e formaggio. Ovviamente, in formato Gran.',
                'price' => 5.50,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/isolated--spicy-gran-crispymcbacon_4.png.webp?itok=U9w53NNv',
            ],
            [
                'id_genre' => 3,
                'id_restaurant' => 1,
                'name' => 'Double Cheeseburger',
                'description' => 'Saranno i due hamburger di carne 100% bovina da allevamenti italiani che abbracciano il formaggio filante, sarà per la cipolla a cubetti, sarà il cetriolo, il ketchup e la senape… il Double Cheeseburger è il Grande Classico che non vi stancherà mai.',
                'price' => 4.50,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/double-cheeseburger--isolated.png.webp?itok=LU-K9h2D',
            ],
            [
                'id_genre' => 3,
                'id_restaurant' => 1,
                'name' => 'Double Chicken BBQ',
                'description' => 'Un must per tutti gli amanti del pollo. Due croccanti fette di pollo impanato fanno da base per il formaggio filante, per la lattuga fresca e per la salsa barbecue. Nasce così un Grande Classico dal gusto affumicato davvero irresistibile.',
                'price' => 3.00,
                'visible' => false,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/double-chicken-bbq--hero-isolated.png.webp?itok=xihIrIGh',
            ],
            [
                'id_genre' => 5,
                'id_restaurant' => 1,
                'name' => 'McFlurry Pistacchio',
                'description' => 'll gusto unico di McFlurry in una nuova versione super golosa, con pistacchio e granella croccante. Tieniti pronto ad un gelato davvero travolgente.',
                'price' => 2.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/mcflurry-pistacchio--isolated.png?itok=IiyP4Ov3',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 1,
                'name' => 'Coca-Cola',
                'description' => 'Coca-Cola alla spina disponibile nei formati 0,25L, 0,4L, 0,5L.',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/isolated--cocacola-medium-branded.png?itok=HTFXyvtK',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 1,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        
            // Burger King
            [
                'id_genre' => 3,
                'id_restaurant' => 2,
                'name' => 'The Speck & Asiago burger',
                'description' => 'Scopri il gusto pieno dello Speck Alto Adige IGP assieme a quello delicato dell\'Asiago DOP che esaltano il nostro delizioso Burger alla griglia arricchito da cipolle fresche fritte e maio gourmet!',
                'price' => 5.50,
                'visible' => true,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/1532_image_it.png?v=',
            ],
            [
                'id_genre' => 3,
                'id_restaurant' => 2,
                'name' => 'Bacon King 3.0. Smokey',
                'description' => 'Se pensi che il bacon non è mai abbastanza, sei sul panino perfetto: prova il gusto inebriante della carne cotta alla griglia, il bacon croccante, la maio normale più la maio al bacon.',
                'price' => 7.50,
                'visible' => true,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/1553_image_it.png?v=',
            ],
            [
                'id_genre' => 3,
                'id_restaurant' => 2,
                'name' => 'The Parmigiano Reggiano Burger',
                'description' => 'Una pioggia di petali di Parmigiano Reggiano DOP sopra un burger da 150 gr di manzo 100% italiano e cotto alla griglia che riposa sulla base di pane e maionese gourmet. E sopra stendiamo un letto di bacon croccante e cipolle fresche fritte con insalata croccante rifinita dalla maionese gourmet.',
                'price' => 6.50,
                'visible' => true,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/570_image_it.png?v=',
            ],
            [
                'id_genre' => 5,
                'id_restaurant' => 2,
                'name' => 'King Fusion M&M\'s',
                'description' => 'King Fusion + toppping al cioccolato e crumble di M&Ms alle arachidi',
                'price' => 3.50,
                'visible' => true,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/1317_image_it.png?v=',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 2,
                'name' => 'Ichnusa',
                'description' => 'Birra chiara non filtrata prodotta in Sardegna. Colore dorato e gusto morbido dalla lieve nota amara. Gradazione alcolica 5,0% vol.',
                'price' => 4.00,
                'visible' => true,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/451_image_it.png?v=',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 2,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        
            // Sushi Li
            [
                'id_genre' => 3,
                'id_restaurant' => 3,
                'name' => 'Nigiri Misto',
                'description' => 'Nigiri Misto 5pz',
                'price' => 6.00,
                'visible' => true,
                'img' => 'https://sushisenpai.it/wp-content/uploads/2017/11/nigiri-sushi.jpg',
            ],
            [
                'id_genre' => 3,
                'id_restaurant' => 3,
                'name' => 'Uramaki Misto',
                'description' => 'Uramaki Misto 8pz',
                'price' => 7.50,
                'visible' => false,
                'img' => 'https://www.modesushi.it/immagini/uramaki-ura-sake.jpg',
            ],
            [
                'id_genre' => 5,
                'id_restaurant' => 3,
                'name' => 'Mochi',
                'description' => 'Mochi a scelta tra gusto fragola, mango, panna, te verde, cocco',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://img.freepik.com/free-photo/black-bean-sweet-dessert-dish_1150-35519.jpg?size=626&ext=jpg&ga=GA1.1.1395880969.1709337600&semt=ais',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 3,
                'name' => 'Heineken',
                'description' => 'Birra Heineken ml 330',
                'price' => 4.00,
                'visible' => false,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/450_image_it.png?v=',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 3,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        
            // Pizzeria Gino Sorbillo
            [
                'id_genre' => 2,
                'id_restaurant' => 4,
                'name' => 'Margherita con pomodorini',
                'description' => 'Pizza margherita con aggiunta di pomodorini e basilico',
                'price' => 4.00,
                'visible' => true,
                'img' => 'https://clipart-library.com/img/1658895.png',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 4,
                'name' => 'Vegetariana',
                'description' => 'Ingredienti: rucola, peperoni, basilico, pomodorini',
                'price' => 5.00,
                'visible' => true,
                'img' => 'https://clipart-library.com/new_gallery/1-15468_large-pizza-with-tomatoes-pizza-images-hd-png.png',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 4,
                'name' => 'Americana piccante',
                'description' => 'Ingredienti: salsiccia, peperoni',
                'price' => 6.00,
                'visible' => false,
                'img' => 'https://clipart-library.com/images/8izrb9RAT.png',
            ],
            [
                'id_genre' => 5,
                'id_restaurant' => 4,
                'name' => 'Torta alla fragola',
                'description' => 'Torta della casa panna e fragole',
                'price' => 4.00,
                'visible' => false,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/1517_image_it.png?v=',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 4,
                'name' => 'Coca-Cola Zero',
                'description' => 'Coca-Cola Zero alla spina disponibile nei formati 0,25L, 0,4L, 0,5L.',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/isolated--cocacola-zero-medium-branded.png?itok=HL2G21l2',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 4,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        
            // Pizza al trancio
            [
                'id_genre' => 2,
                'id_restaurant' => 5,
                'name' => 'Americana',
                'description' => 'Ingredienti: rossa con salsiccia.',
                'price' => 4.00,
                'visible' => true,
                'img' => 'https://clipart-library.com/images_k/pizza-transparent-background/pizza-transparent-background-24.png',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 5,
                'name' => 'Margherita',
                'description' => 'Margherita classica con impasto lievitato 48h.',
                'price' => 4.00,
                'visible' => true,
                'img' => 'https://clipart-library.com/img/1658895.png',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 5,
                'name' => 'Gorgonzola con verdure',
                'description' => 'Ingredienti: bianca con gorgonzola e verdure grigliate.',
                'price' => 4.00,
                'visible' => true,
                'img' => 'https://clipart-library.com/image_gallery2/Pizza-Download-PNG.png',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 5,
                'name' => 'Coca-Cola Zero',
                'description' => 'Coca-Cola Zero alla spina disponibile nei formati 0,25L, 0,4L, 0,5L.',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/isolated--cocacola-zero-medium-branded.png?itok=HL2G21l2',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 5,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        
            // Ristorante Migasa
            [
                'id_genre' => 1,
                'id_restaurant' => 6,
                'name' => 'Antipasto della casa',
                'description' => 'Salumi e formaggi della casa',
                'price' => 9.00,
                'visible' => true,
                'img' => 'https://static.vecteezy.com/system/resources/previews/036/498/029/original/ai-generated-a-classic-italian-antipasto-platter-with-olives-on-transparent-background-free-png.png',
            ],
            [
                'id_genre' => 1,
                'id_restaurant' => 6,
                'name' => 'Bruschetta al pomodoro',
                'description' => 'Bruschetta fatta in casa con pomodoro di prima qualità',
                'price' => 7.00,
                'visible' => false,
                'img' => 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvcHg4NjU5MzktaW1hZ2Uta3d2eGQyeTIuanBn.jpg',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 6,
                'name' => 'Spaghetti ai frutti di mare',
                'description' => 'Spaghetti n.3 ai frutti di mare',
                'price' => 8.00,
                'visible' => true,
                'img' => 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvay1wLTIyMi1ha2UtMDA5LmpwZw.jpg',
            ],
            [
                'id_genre' => 5,
                'id_restaurant' => 6,
                'name' => 'Torta alla fragola',
                'description' => 'Torta della casa panna e fragole',
                'price' => 4.00,
                'visible' => false,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/1517_image_it.png?v=',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 6,
                'name' => 'Coca-Cola',
                'description' => 'Coca-Cola alla spina disponibile nei formati 0,25L, 0,4L, 0,5L.',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/isolated--cocacola-medium-branded.png?itok=HTFXyvtK',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 6,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        
            // Ristorante Rock 'N' Roll
            [
                'id_genre' => 1,
                'id_restaurant' => 7,
                'name' => 'Antipasto della casa',
                'description' => 'Salumi e formaggi della casa',
                'price' => 9.00,
                'visible' => true,
                'img' => 'https://static.vecteezy.com/system/resources/previews/036/497/910/non_2x/ai-generated-a-classic-italian-antipasto-platter-with-olives-on-transparent-background-free-png.png',
            ],
            [
                'id_genre' => 1,
                'id_restaurant' => 7,
                'name' => 'Bruschetta al pomodoro',
                'description' => 'Bruschetta fatta in casa con pomodoro di prima qualità',
                'price' => 7.00,
                'visible' => false,
                'img' => 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvcHg4NjU5MzktaW1hZ2Uta3d2eGQyeTIuanBn.jpg',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 7,
                'name' => 'Spaghetti ai frutti di mare',
                'description' => 'Spaghetti n.3 ai frutti di mare',
                'price' => 8.00,
                'visible' => true,
                'img' => 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvay1wLTIyMi1ha2UtMDA5LmpwZw.jpg',
            ],
            [
                'id_genre' => 5,
                'id_restaurant' => 7,
                'name' => 'Torta alla fragola',
                'description' => 'Torta della casa panna e fragole',
                'price' => 4.00,
                'visible' => false,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/1517_image_it.png?v=',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 7,
                'name' => 'Coca-Cola',
                'description' => 'Coca-Cola alla spina disponibile nei formati 0,25L, 0,4L, 0,5L.',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/isolated--cocacola-medium-branded.png?itok=HTFXyvtK',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 7,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        
            // Ristorante Piedra del Sol
            [
                'id_genre' => 1,
                'id_restaurant' => 8,
                'name' => 'Antipasto della casa',
                'description' => 'Salumi e formaggi della casa',
                'price' => 9.00,
                'visible' => true,
                'img' => 'https://static.vecteezy.com/system/resources/previews/036/497/910/non_2x/ai-generated-a-classic-italian-antipasto-platter-with-olives-on-transparent-background-free-png.png',
            ],
            [
                'id_genre' => 1,
                'id_restaurant' => 8,
                'name' => 'Bruschetta al pomodoro',
                'description' => 'Bruschetta fatta in casa con pomodoro di prima qualità',
                'price' => 7.00,
                'visible' => false,
                'img' => 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvcHg4NjU5MzktaW1hZ2Uta3d2eGQyeTIuanBn.jpg',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 8,
                'name' => 'Spaghetti ai frutti di mare',
                'description' => 'Spaghetti n.3 ai frutti di mare',
                'price' => 8.00,
                'visible' => true,
                'img' => 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvay1wLTIyMi1ha2UtMDA5LmpwZw.jpg',
            ],
            [
                'id_genre' => 5,
                'id_restaurant' => 8,
                'name' => 'Torta alla fragola',
                'description' => 'Torta della casa panna e fragole',
                'price' => 4.00,
                'visible' => false,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/1517_image_it.png?v=',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 8,
                'name' => 'Coca-Cola',
                'description' => 'Coca-Cola alla spina disponibile nei formati 0,25L, 0,4L, 0,5L.',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/isolated--cocacola-medium-branded.png?itok=HTFXyvtK',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 8,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        
            // Ristorante Maya
            [
                'id_genre' => 1,
                'id_restaurant' => 9,
                'name' => 'Antipasto della casa',
                'description' => 'Salumi e formaggi della casa',
                'price' => 9.00,
                'visible' => true,
                'img' => 'https://static.vecteezy.com/system/resources/previews/036/497/910/non_2x/ai-generated-a-classic-italian-antipasto-platter-with-olives-on-transparent-background-free-png.png',
            ],
            [
                'id_genre' => 1,
                'id_restaurant' => 9,
                'name' => 'Bruschetta al pomodoro',
                'description' => 'Bruschetta fatta in casa con pomodoro di prima qualità',
                'price' => 7.00,
                'visible' => true,
                'img' => 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvcHg4NjU5MzktaW1hZ2Uta3d2eGQyeTIuanBn.jpg',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 9,
                'name' => 'Spaghetti ai frutti di mare',
                'description' => 'Spaghetti n.3 ai frutti di mare',
                'price' => 8.00,
                'visible' => true,
                'img' => 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvay1wLTIyMi1ha2UtMDA5LmpwZw.jpg',
            ],
            [
                'id_genre' => 5,
                'id_restaurant' => 9,
                'name' => 'Torta alla fragola',
                'description' => 'Torta della casa panna e fragole',
                'price' => 4.00,
                'visible' => true,
                'img' => 'https://www.burgerking.it/assets/img/console/mo/products/1517_image_it.png?v=',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 9,
                'name' => 'Coca-Cola',
                'description' => 'Coca-Cola alla spina disponibile nei formati 0,25L, 0,4L, 0,5L.',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/isolated--cocacola-medium-branded.png?itok=HTFXyvtK',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 9,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        
            // Ristorante Miao Chinese
            [
                'id_genre' => 2,
                'id_restaurant' => 10,
                'name' => 'Xiaolongbao',
                'description' => 'Ravioli con carne',
                'price' => 8.00,
                'visible' => true,
                'img' => 'https://images.rawpixel.com/image_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvbHIvcHg3Nzg4ODYtaW1hZ2Uta3d2eGZ5bnIuanBn.jpg',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 10,
                'name' => 'Asian Noodles',
                'description' => 'Noodles con uova e gamberi',
                'price' => 7.00,
                'visible' => true,
                'img' => 'https://static.vecteezy.com/system/resources/thumbnails/010/834/003/small/instant-noodles-with-grilled-mushrooms-in-black-bowl-top-view-free-png.png',
            ],
            [
                'id_genre' => 2,
                'id_restaurant' => 10,
                'name' => 'Noodeles di pollo',
                'description' => 'Classici noodles con pollo e curry',
                'price' => 10.00,
                'visible' => true,
                'img' => 'https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIyLTA0L3Vwd2s2MTY2MDQ5Ny13aWtpbWVkaWEtaW1hZ2Uta293cmYzamcuanBn.jpg',
            ],
            [
                'id_genre' => 5,
                'id_restaurant' => 10,
                'name' => 'Mochi',
                'description' => 'Mochi a scelta tra gusto fragola, mango, panna, te verde, cocco',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://img.freepik.com/free-photo/black-bean-sweet-dessert-dish_1150-35519.jpg?size=626&ext=jpg&ga=GA1.1.1395880969.1709337600&semt=ais',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 10,
                'name' => 'Coca-Cola',
                'description' => 'Coca-Cola alla spina disponibile nei formati 0,25L, 0,4L, 0,5L.',
                'price' => 3.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/isolated--cocacola-medium-branded.png?itok=HTFXyvtK',
            ],
            [
                'id_genre' => 6,
                'id_restaurant' => 10,
                'name' => 'Acqua Naturale',
                'description' => 'Acqua minerale',
                'price' => 1.00,
                'visible' => true,
                'img' => 'https://www.mcdonalds.it/sites/default/files/styles/product_isolated_preview/public/products/acqua-lilla_isolated.png?itok=VLnuTPh4',
            ],
        ];

        foreach ($Dishes as $item) {

            Dish::create([
                'genre_id' => $item['id_genre'],
                'restaurant_id' => $item['id_restaurant'],
                'name' => $item['name'],
                'slug' => Str::slug($item['name'] . '-'),
                'description' => $item['description'],
                'price' => $item['price'],
                'visible' => $item['visible'],
                'image' => $item['img']
            ]);
        } 
    }
}
